from __future__ import annotations

import json
import re
from collections import Counter
from dataclasses import dataclass

from rc2ui.naming.map import NamingKind


@dataclass(frozen=True, slots=True)
class NamingSuggestion:
    kind: NamingKind
    source_regex: str
    dialog_regex: str
    source_id: str
    object_name: str
    occurrence: int | None
    confidence: float
    derived_from: str


def emit_naming_suggestions(
    suggestions: tuple[NamingSuggestion, ...],
) -> str:
    lines = [
        "# Generated by rc2ui; merge reviewed rules into rc2ui.toml.",
    ]
    groups: dict[
        tuple[NamingKind, str, str],
        list[NamingSuggestion],
    ] = {}
    repeated: list[NamingSuggestion] = []
    for suggestion in suggestions:
        if suggestion.occurrence is not None:
            repeated.append(suggestion)
            continue
        key = (
            suggestion.kind,
            suggestion.source_regex,
            suggestion.dialog_regex,
        )
        groups.setdefault(key, []).append(suggestion)

    rule_number = 0
    for (kind, source_regex, dialog_regex), entries in groups.items():
        rule_number += 1
        lines.extend(
            _group_header(
                rule_number,
                kind=kind,
                source_regex=source_regex,
                dialog_regex=dialog_regex,
            )
        )
        lines.append("[naming.rules.names]")
        for entry in entries:
            lines.append(
                f"{_toml_key(entry.source_id)} = "
                + _inline_value(entry)
            )

    repeated_names = Counter(entry.object_name for entry in repeated)
    for entry in repeated:
        rule_number += 1
        suffix = _rule_suffix(entry.object_name)
        if repeated_names[entry.object_name] > 1:
            suffix += f"-{entry.occurrence}"
        lines.extend(
            (
                "",
                "[[naming.rules]]",
                f"name = {_toml_string(f'suggested-{rule_number:05d}-{suffix}')}",
                f"kind = {_toml_string(entry.kind.value)}",
                f"source_regex = {_toml_string(entry.source_regex)}",
                f"dialog_regex = {_toml_string(entry.dialog_regex)}",
                f"id_regex = {_toml_string(re.escape(entry.source_id))}",
                f"occurrence = {entry.occurrence}",
                f"name_template = {_toml_string(entry.object_name)}",
                f"confidence = {entry.confidence:.2f}",
                f"derived_from = {_toml_string(entry.derived_from)}",
            )
        )
    return "\n".join(lines) + "\n"


def _group_header(
    rule_number: int,
    *,
    kind: NamingKind,
    source_regex: str,
    dialog_regex: str,
) -> tuple[str, ...]:
    return (
        "",
        "[[naming.rules]]",
        f"name = {_toml_string(f'suggested-{rule_number:05d}-{kind.value}-names')}",
        f"kind = {_toml_string(kind.value)}",
        f"source_regex = {_toml_string(source_regex)}",
        f"dialog_regex = {_toml_string(dialog_regex)}",
        "",
    )


def _inline_value(suggestion: NamingSuggestion) -> str:
    return (
        "{ name = "
        + _toml_string(suggestion.object_name)
        + f", confidence = {suggestion.confidence:.2f}, derived_from = "
        + _toml_string(suggestion.derived_from)
        + " }"
    )


def _rule_suffix(object_name: str) -> str:
    return object_name.replace("_", "-")


def _toml_key(value: str) -> str:
    if re.fullmatch(r"[A-Za-z0-9_-]+", value):
        return value
    return _toml_string(value)


def _toml_string(value: str) -> str:
    # JSON basic strings are a strict subset of TOML basic strings for the
    # characters emitted here and safely escape regex backslashes.
    return json.dumps(value, ensure_ascii=False)
